parameters:
  - name: location
    displayName: Resource Location To Create Initial Assets In?
    type: string
    default: "East US"

  - name: subscriptionId
    displayName: Subscription ID To Create Initial Assets In?
    type: string
    default: Visual Studio Enterprise Subscription
    values:
      - Visual Studio Enterprise Subscription

  - name: resourceGroupName
    displayName: New/Existing Resource Group Name To Create Initial Assets In?
    type: string
    #default: rg-kcns-<AppName>-<Environment>-<Location>-<InstanceCount>
    #default: Takes primary resource group and secondary resource groups e.g rg1,rg2,..
    default: rg-finops-kcl-eastus-001,rg-kcns-blob-0107,rg-kcns-blob-0108

  - name: servicePrincipalName
    displayName: New Service Principal Name For Child Pipeline and Service Connection Creation?
    type: string
    default: sp-kcns-<AppName>-<Environment>-<Location>-<InstanceCount>

  - name: yourTenantConfiguredEmailAddress
    displayName: Your Email Address Configured For Sandbox Tenant?
    type: string
    default: oluwaseuniyadi@gmail.com

  - name: storageAccount
    displayName: New Storage Account Name?
    type: string
    default: stkcns<AppName><InstanceCount>

  - name: storageAccountContainer
    displayName: New Storage Account Container Name To Store TF State File In?
    type: string
    default: development

  - name: keyVaultName
    displayName: Key vault Name For Child Pipeline Key vault Values?
    type: string
    default: kv-kcns-<AppName>-<Environment>-<Location>-<InstanceCount>

  - name: appIDKeyVaultName
    displayName: New Service Principal App ID Key vault Name?
    type: string
    default: kv-app-id

  - name: secretKeyVaultName
    displayName: New Service Principal Secret Key vault Name?
    type: string
    default: kv-secret

  - name: objectIDKeyVaultName
    displayName: New Service Principal Object ID Key vault Name?
    type: string
    default: kv-obj-id

  - name: gitPatKeyVaultName
    displayName: New Service Principal GIT PAT Key vault Name?
    type: string
    default: kv-git-pat

  - name: storageKeyIDKeyVaultName
    displayName: New Service Principal Storage Account Key Key vault Name?
    type: string
    default: kv-storage-key

variables:
  # - name: ownerServicePrincipalName
  #   value: azure-service-conn
  # - name: existingKeyvault
  #   value: kv-kcns-common
  - name: roleDefinition
    value: Contributor

trigger: none
pr: none

resources:
  repositories:
    - repository: self
      type: git
      ref: main
jobs:
  - job: Job_1
    displayName: Create Initial Assets
    steps:
      - checkout: self
        clean: true
        fetchTags: false
      - task: AzurePowerShell@5
        displayName: "Azure PowerShell Task"
        inputs:
          azureSubscription: azure-service-conn
          azurePowerShellVersion: LatestVersion
          scriptPath: $(System.DefaultWorkingDirectory)/create-initial-asset.ps1
          scriptArguments: -location "${{ parameters.location }}" `

            -subscriptionId "${{ parameters.subscriptionId }}" `

            -resourceGroupName "${{ parameters.resourceGroupName }}" `

            -servicePrincipalName "${{ parameters.servicePrincipalName }}" `

            -keyVaultName "${{ parameters.keyVaultName }}" `

            -storageAccount "${{ parameters.storageAccount }}" `

            -storageAccountContainer "${{ parameters.storageAccountContainer }}" `

            -yourTenantConfiguredEmailAddress "${{ parameters.yourTenantConfiguredEmailAddress }}"

            -appIDKeyVaultName "${{ parameters.appIDKeyVaultName }}" `

            -secretKeyVaultName "${{ parameters.secretKeyVaultName }}" `

            -objectIDKeyVaultName "${{ parameters.objectIDKeyVaultName }}" `

            -gitPatKeyVaultName "${{ parameters.gitPatKeyVaultName }}" `

            -storageKeyIDKeyVaultName "${{ parameters.storageKeyIDKeyVaultName }}" `

            -roleDefinition "${{ parameters.roleDefinition }}" `
